### ISSUE TITLE
[BUG] Reply partial broken

### ISSUE THREAD

**Issue by Kr328** [duo/matrix-qq#1]
回复消息功能似乎存在问题

### Matrix -> QQ (群组和私聊)
回复的消息中引用的消息会变为纯文本的 `Reply`
如下图所示第一条消息为 **从 Matrix 发出**
第二条消息为 **TIM 发出**
![截图 2022-10-01 14-06-56](https://user-images.githubusercontent.com/39107975/193395608-7543b8a7-d464-42ef-be77-4951d7d7bc29.png)
![Screenshot_20221001-135416_TIM](https://user-images.githubusercontent.com/39107975/193395622-c78d73ed-7131-4c3c-94c3-89c258b6efa3.png)

### QQ -> Matrix (私聊)
会直接丢失回复的消息
![截图 2022-10-01 14-01-36](https://user-images.githubusercontent.com/39107975/193395735-3bd2da0f-a0a8-4845-8efe-c6449374806e.png)
![Screenshot_20221001-135957_TIM](https://user-images.githubusercontent.com/39107975/193395698-2f902320-39c6-4216-8869-035d8c8496d0.png)

### 正在使用的版本
```
REPOSITORY                       TAG       IMAGE ID       CREATED       SIZE
matrixdotorg/synapse             latest    153ea0d63222   3 days ago    399MB
lxduo/matrix-qq                  latest    515f44138c1c   6 days ago    127MB
caddy                            latest    7d8159c96a82   8 days ago    46.6MB
postgres                         14        75993dd36176   2 weeks ago   376MB
```

**Comment by duo** [comment]
嗯, 因为没有记录原始消息, 所以回复的时候先用 Reply 当占位符了, 导致 iOS 上可以看到正确的回复, 但是 Android 不支持
这个会抽空修复, 但是应该也只会支持原始消息是文本的

**Comment by duo** [comment]
@Kr328  在 https://github.com/duo/matrix-qq/commit/351528db1a7d19926fc545776918b452fd8c9616 移除了 Reply 这个占位符
目前 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 的群回复支持的还全, 但是私聊的回复支持的不是很好 (跳转异常, 非文本消息显示)

然后 QQ -> Matrix (私聊) 丢失回复 是怎么操作的呢? 我这没法复现...

**Comment by Kr328** [comment]
就是**好友**在 QQ 上回复**好友自己的**或者**我的**消息会丢失回复

顺便贴上登录 QQ 用的 device.json
```json
{"display":"MIRAI.912413.001","product":"mirai","device":"mirai","board":"mirai","model":"mirai","finger_print":"mamoe/mirai/mirai:10/MIRAI.200122.001/7440925:user/release-keys","boot_id":"da594a75-9b11-927b-52c6-41233fb51f23","proc_version":"Linux version 3.0.31-tdAmcTZZ (android-build@xxx.xxx.xxx.xxx.com)","protocol":5,"imei":"827002043888523","brand":"mamoe","bootloader":"unknown","base_band":"","version":{"incremental":"5891938","release":"10","codename":"REL","sdk":29},"sim_info":"T-Mobile","os_type":"android","mac_address":"00:50:56:C0:00:08","ip_address":[10,0,1,3],"wifi_bssid":"00:50:56:C0:00:08","wifi_ssid":"\\u003cunknown ssid\\u003e","imsi_md5":"0b6fc758154e387fca855454bf11da98","android_id":"008660b3e1aeeba3","apn":"wifi","vendor_name":"MIUI","vendor_os_name":"mirai"}
```

**Comment by duo** [comment]
这个有点诡异了, 我怎么都复现不了...
你那边方便在 config.yaml 把日志的 print_level 设置成 debug, 然后看看回复的时候, 会不会有以下日志呢
```
Portal(1234567u7654321u) handled message seq(18218) id(187638456) ts(1664716230) -> $QHLwNLBTsb4widTKOwT5Cg0Cczc2DmzWriqEpjA2MXI
Portal(1234567u7654321u) query message seq(18218) ts(1664716230)
```
如果和号码 7654321 的私聊回复正常的话, 那么同个 seq 和 ts 的应该有两条这样的日志才对

**Comment by Kr328** [comment]
今天 pull 之后的版本似乎已经正常了
