### ISSUE TITLE
无法同步来自于其他设备主动发送的聊天

### ISSUE THREAD

**Issue by Kerwin1202** [duo/matrix-qq#11]
虽然部署了这个，但是有时候手机或者电脑还是用的原生 QQ 主动给群或者单个用户发消息，这个本人主动发的 不会出现在matrix 里。

https://github.com/Mrs4s/MiraiGo 是基于  [go-cqhttp](https://github.com/Mrs4s/go-cqhttp)  ，以前部署过 似乎配置有有一个 `report-self-message: true` 上报自身发言，不知道是否因为类似的未开启

**Comment by duo** [comment]
上报自身发言目前是一直开启的 https://github.com/duo/matrix-qq/blob/master/internal/user.go#L363, 我这本人主动发的都会出现在 matrix 里的
可以检查下 matrix-qq 的日志, 看有没有什么出错信息可以排查的
如果啥错误信息都没有, 那可能 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 库那就没获取到自身发送的消息

**Comment by duo** [comment]
看了下, 有一些问题哈

1. double puppeting 这块, 把 `double_puppet_server_map` 和 `login_shared_secret_map` 下的 `example.com` 这个改成你的域名呐
2. 也不知道你是不是有做 [delegation](https://github.com/matrix-org/synapse/blob/develop/docs/delegate.md), 如果你的 homeserver.yaml 里配置的 server_name 是 `xxx.com` 的话,  那么 qq-registration.yaml 下的相关配置, 除了那些要填 `https://matrix.xxx.com` 的地方外, 别的地方都应该是 `xxx.com` 而不是 `matrix.xxx.com`, 和 server_name 保持一致
3. sync_with_custom_puppets 这个不是关键配置
4. 最后的图里的日志, matrix-qq 没连上你的 postgres 数据库

**Comment by Kerwin1202** [comment]
多谢

1. 我看文档  `double_puppet_server_map` 和 `login_shared_secret_map` 下的 `example.com`  这两个的 没有引号我以为就写死的不能改
2.   最后图里的那个 显示 的 ip 都不是我服务器的 ip 我昨天还是前天部署的时候都正常，期间未做过任何操作 `uri: postgres://root:xxxx@postgres/matrix_qq?sslmode=disable`. 我再摸索下
3. 我微信有几千人，所以想要 `search somebody` 每次都微信报错闪退，不知道是否是循环的时候加载太快导致的。我以前用过此处代码 并无此问题 [CGetFriendList](https://github.com/ljc545w/ComWeChatRobot/blob/c43b82078d07230524568fad44825e3868afef19/old_projects/wxRobot/Program.cs#L86)

**Comment by duo** [comment]
> 3. 我微信有几千人，所以想要 `search somebody` 每次都微信报错闪退，不知道是否是循环的时候加载太快导致的。我以前用过此处代码 并无此问题 [CGetFriendList](https://github.com/ljc545w/ComWeChatRobot/blob/c43b82078d07230524568fad44825e3868afef19/old_projects/wxRobot/Program.cs#L86)

可以考虑把闪退的报错信息和对应的 dmp 文件之类的提交给 ComWeChatRobot 呐

> 4. 不管微信或者是 QQ 发现并未同步备注信息，看到的都是对方 QQ、微信的名字，不知道是否我没配置好，还是不支持( 搜索的时候无备注比较麻烦）

这个参考 https://github.com/duo/matrix-wechat/issues/6

> 5. 想问下如果想要配置 第二个 QQ、微信 配置上是否有什么区分之类的 比如下图
> 
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/16319833/205669028-61ef7dc7-b79c-4125-923c-4b3b6154d90b.png">

简单过了下要改的地方
config.yaml:
`appservice.address`, `appservice.database.uri`, `appservice.id`, `appservice.bot.username`, `appservice.as_token`, `appservice.hs_token`, `bridge.username_template`, `bridge.listen_address (matrix-wechat)`
registration.yaml:
`namespaces.users.regex`

**Comment by Kerwin1202** [comment]
多谢，自身发言上报没做过任何操作，（期间可能就重新 restart docker）反正现在好了，所以关了先
