### ISSUE TITLE
A release for non-docker users?

### ISSUE THREAD

**Issue by yuandi42** [duo/matrix-qq#20]
First, thank you for your work. Can you provide a prebuilt executable of matrix-qq (as well as matrix-wechat) since there are people like me who don't or can't use docker on their servers?

Though compiling manually is an option, it's little hard and messy (installing golang on Debian-based machine kinds of suck). And I think using a prebuilt release would be a lot better.

Any help would be appreciated.

**Comment by duo** [comment]
done
https://github.com/duo/matrix-qq/releases
https://github.com/duo/matrix-wechat/releases

**Comment by yuandi42** [comment]
Thanks!
