### ISSUE TITLE
关于gocqhttp项目的问题

### ISSUE THREAD

**Issue by yunkuangao** [duo/matrix-qq#30]
根据 https://github.com/Mrs4s/go-cqhttp/issues/2471 的说明，推荐迁移到 [Chronocat](https://chronocat.vercel.app/) 上,可能在未来某个时间段腾讯直接将sign方案给彻底封杀？

**Comment by duo** [comment]
等新的稳定吧, 跑 headless 的话, 照着`matrix-wechat` 的方式改改就能用了
