### ISSUE TITLE
群聊中所有回复消息和图文消息都会标记为提及

### ISSUE THREAD

**Issue by SeraphJACK** [duo/matrix-qq#4]
群聊中回复别人的消息、单条同时包含图片和文本的消息都会标记为提及本人

**Comment by duo** [comment]
请问这个回复的操作，是在 matrix 上回复, 还是在 QQ 上回复呢?
如果是后者的话, 这个同时包含图片和文本的消息, 是原文, 还是回复的消息?

**Comment by SeraphJACK** [comment]
> 请问这个回复的操作，是在 matrix 上回复, 还是在 QQ 上回复呢？

QQ 上的回复

> 如果是后者的话, 这个同时包含图片和文本的消息, 是原文, 还是回复的消息?

QQ 上发送的同时包含图片和文本的消息在 matrix 上就会显示为提及我，无论是否回复

---

<img width="212" alt="image" src="https://user-images.githubusercontent.com/25274081/198445466-6abc932a-ff62-456f-a1fe-77daf0f03e60.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/25274081/198445519-e439e3dc-b952-41fd-8c10-c6db7cb5af72.png">

**Comment by duo** [comment]
![image](https://user-images.githubusercontent.com/18750/198487497-33e3c256-5e42-4e5e-ad96-ef4f21c91f76.png)
<img width="703" alt="Screen Shot 2022-10-28 at 10 59 37" src="https://user-images.githubusercontent.com/18750/198489671-c4640365-ac6d-4f40-b6b1-061782e280d7.png">
我这看到 matrix 和 QQ 的表现是一致的呐

然后第二个图那个"msg with a picture"有什么问题么? 我没看到有什么 @ 之类的提及呐

**Comment by SeraphJACK** [comment]
消息为红色的，在房间通知设置为仅提及或关键字时也会推送通知

**Comment by duo** [comment]
被引用的消息的发言人会收到通知这种是 matrix 客户端的行为
然后图文混排消息会提及本人这个我没法重现, 在代码里是没什么特殊处理的, 最终也是看客户端的行为

**Comment by SeraphJACK** [comment]
> 被引用的消息的发言人会收到通知这种是 matrix 客户端的行为

但是图里引用的发言人不是我，但是我也会收到通知？

**Comment by duo** [comment]
> > 被引用的消息的发言人会收到通知这种是 matrix 客户端的行为
> 
> 但是图里引用的发言人不是我，我也会收到通知？

不会，可重现的话去对应的 matrix 客户端报 bug 吧

**Comment by SeraphJACK** [comment]
看了一下消息，是 Element 客户端对 custom html 类型消息的处理有 bug ，确实不是 matrix-qq 的问题

**Comment by SeraphJACK** [comment]
破案了，是 hs name 里有用户名会导致这种情况，，，
