### ISSUE TITLE
与qq bridge bot的聊天窗口不显示消息

### ISSUE THREAD

**Issue by oatiz** [duo/matrix-qq#7]
聊天室:
---
<img width="725" alt="image" src="https://user-images.githubusercontent.com/24953151/199255575-d4f16fa2-8cb3-4c1d-908f-ec97c2f3a0cf.png">

机器日志:
---
<img width="790" alt="image" src="https://user-images.githubusercontent.com/24953151/199255820-a7a51bc0-ff39-4c1f-9816-4e16580fce94.png">

可能触发此问题的原因:
---
误删了与机器人的初始聊天室，再次与机器人创建新聊天室出现了此问题。

**Comment by duo** [comment]
```[CommandProcessor/DEBUG] @xxx:matrix.org sent "list groups 1 50" in ROOM地址``` 和 ```req #107105 PUT https://matrix.xiaoduo.me/_matrix/client/v3/rooms/ROOM地址/send/m.room.message/``` 以及你当前聊天室的 **ROOM地址** 一致么?

**Comment by oatiz** [comment]
> [Nov  2, 2022 12:04:05] [CommandProcessor/DEBUG] @lyraile:matrix.org sent "help" in !FLHAXJApfOQbKqAbsL:matrix.org
> [Matrix/Bot/DEBUG] req #108766: PUT https://matrix.lyraile.org/_matrix/client/v3/rooms/%21FLHAXJApfOQbKqAbsL:matrix.org/send/m.room.message

---
不一致的，`FLHAXJApfOQbKqAbsL`与`21FLHAXJApfOQbKqAbsL`

**Comment by duo** [comment]
```%21``` 是 ```!``` 的转义, 所以这两个是一致的
从 !FLHAXJApfOQbKqAbsL:matrix.org 收到消息, 然后消息也发回到了 !FLHAXJApfOQbKqAbsL:matrix.org 去了, 如果这日志后面没报错的话, 说明 bridge 的处理没啥问题
那么得看看 matrix 服务器那边的日志了, 有没有啥报错之类的
